project:
  type: website

website:
  title: "Daniel D'souza"
  site-url: https://dsouzadaniel.github.io/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dsouzadaniel/
      - icon: twitter
        href: https://twitter.com/mrdanieldsouza

format:
  html:
    theme: litera
    css: styles.css



